import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const client: string = "db7d70beb5d14841b699b7df68b56a1c";
  const secret: string = "1316d41696ed444f88a9365c755eb8f2";
  const redirect: string = "http://localhost:3000/callback";
  const scope: string =
    "user-read-private user-read-email user-read-playback-position user-top-read user-read-recently-played";

  const generateRandomString = (length: number) => {
    let text: string = "";
    const possible: string =
      "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";

    for (let i: number = 0; i < length; i++) {
      text += possible.charAt(Math.floor(Math.random() * possible.length));
    }
    return text;
  };

  const query = `response_type=code&client_id=${client}&scope=${scope}&redirect_uri=${redirect}&state=${generateRandomString(
    16
  )}`;

  const completeURL: string =
    `https://accounts.spotify.com/en/authorize?${JSON.stringify(
      query
    )}`.replace('"', "");

  return (
    <div className={styles.container}>
      <Head>
        <title>Spotify Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="text-xxxl text-gray-500">
        <a href={completeURL}>Login</a>
      </div>
    </div>
  );
};

export default Home;
