import type { NextPage } from "next";
import Head from "next/head";
import Logo from "../imgs/Spotify_Icon_RGB_White.png";
import { useState, useEffect } from "react";
import Image from "next/image";
import styles from "../styles/Home.module.css";

interface TheState {
  errors: boolean;
}

const Home: NextPage = () => {
  const [errors, updateErr] = useState<TheState>({ errors: false });
  useEffect(() => {
    if (window.location.search === "?error" && !errors.errors) {
      updateErr({ errors: true });
    }
  });

  const client: string = "db7d70beb5d14841b699b7df68b56a1c";
  const secret: string = "1316d41696ed444f88a9365c755eb8f2";
  const redirect: string = "http://localhost:3000/callback";
  const scope: string =
    "user-read-private user-read-email user-read-playback-position user-top-read user-read-recently-played user-follow-read";

  const generateRandomString = (length: number) => {
    let text: string = "";
    const possible: string =
      "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";

    for (let i: number = 0; i < length; i++) {
      text += possible.charAt(Math.floor(Math.random() * possible.length));
    }
    return text;
  };

  const query = `response_type=code&client_id=${client}&scope=${scope}&redirect_uri=${redirect}&state=${generateRandomString(
    16
  )}`;

  const completeURL: string =
    `https://accounts.spotify.com/en/authorize?${JSON.stringify(
      query
    )}`.replace('"', "");

  const errorHandle = () => {
    if (errors.errors) {
      return (
        <h1 className="text-red-500 text-center">
          There has been an error, please try logging in again
        </h1>
      );
    }
  };
  return (
    <div className="">
      <Head>
        <title>Spotify Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="mx-auto w-4/5 mt-64">
        <img
          src={Logo.src}
          alt="Spotify Logo in White"
          className="h-28 mx-auto"
        />
        <h1 className="text-white text-3xl text-center mt-10 font-bold mx-auto spotifyBold">
          Spotify Profile
        </h1>
        <a
          className=" mx-auto mt-12 mb-10 text-md px-6 h-10 w-56 pl-10 pt-2 block text-white spotifyBold font-semibold bgSpotifyGreen rounded-full hover:scale-110 duration-700"
          href={completeURL}
        >
          Log in to Spotify
        </a>
        {errorHandle()}
      </div>
    </div>
  );
};

export default Home;
